
const unwantedZz66 = [
    'huuli ', 'jymy-sarjat ', 'tex ', 'villi länsi' ]

const stripBuyNowItems = [

    'avaruuden korkeajännitys',
    'Avaruuden Tarzan',
    'huuli ',
    'james bond',
    'joulumanteli',
    'jouluparaati',
    'judge dredd',
    'juhlanumero',
    'jymy ' /*HUOM! JYMY */,
    'jymy-sarjat',
    'kädet ylös' /* HUOM! KÄDET YLÖS */,
    'lassi ja leevi',
    'lucky luke', 
    'mini-taskari',
    'mokkeri',
    'muumi ' /* HUOM! MUUMI */,
    'nakke ',
    'perry rhodan ',
    'pikku riku',
    'raf ',
    'robin hood',
    'roope setä ',
    'roope-setä ',
    /* 'roope-setä 6',
    'roope-setä 7',
    'roope-setä 8',
    'roope-setä 09',
    'roope-setä 12', */
    'sarjakirja' /* HUOM! SARJAKIRJA */,
    'Siivet ',
    'taskarit',
    'taskukirj' /* HUOM TASKUKIRJA/-JOJA/-T */,
    'taskulehti',
    'tenavat' /* HUOM! TENAVAT */,
    'Teräsnyrkki ',
    'tex willer',
    'texas ',
    'tintin ',
    'tintti ',
    'valerian' /* valerian */,
    'villi länsi ',
    'x-men',
    'yoko tsuno',
    ' - 1980', // puree välilyönneillä yhteen Aku Ankka caseen
    '1985', '1986', '1987', '1988', '1989', '199', '200', '201',
    '/85', '/86', '/87', '/88', '/89', 
    '/90', '/91', '/92', '/93', '/94', '/95', '/96', '/97', '/98', '/99',
]
